export const metadata = {
  title: 'Vibe Guestbook',
  description: 'Generated by Antigravity',
}

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body>{children}</body>
    </html>
  )
}
